import '@rainbow-me/rainbowkit/styles.css'
import './globals.css'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/providers/ThemeProvider'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { WalletProvider } from '@/providers/WalletProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Raindrop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <WalletProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="min-h-screen flex flex-col">
              {children}
            </main>
            <Footer />
          </ThemeProvider>
        </WalletProvider>
      </body>
    </html>
  )
}